config/routes.rb
Clonemarks::Application.routes.draw do

  get "emails/create"

  devise_for :users

  resources :topics

  resources :bookmarks do
  	resources :likes
  end

  get "welcome/index"

  get "topics/index"

  get "likes/new"

  post '/emails' => 'emails#create'

  root :to => 'topics#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    # if a member, they can manage their own posts 
    # (or create new ones)
    if user.role? :member
      can :manage, Bookmark, :user_id => user.id
      can :manage, Like, :user_id => user.id
      can :manage, Topic, :user_id => user.id
    end

    # Admins can do anything
    if user.role? :admin
      can :manage, :all
    end

    can :read, :all
  end
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  
  has_many :likes, dependent: :destroy
  attr_accessible :name, :url, :user, :topic

  scope :desc, order("bookmarks.updated_at DESC")

  def self.new_from_email(mail)
  	bookmark = nil
  	# get the user from the e-mail address
    Rails.logger.info ">>> email address is: #{mail.from.first}"
    user = User.find_by_email(mail.from.first)
    if user 
      bookmark = Bookmark.new
      bookmark.user = user
      Rails.logger.info ">>>> Bookmark user: #{bookmark.user.inspect}"
      # strip the tag off the subject and set it as subject
      bookmark.topic = Topic.where(name: mail.subject.gsub(/#/, '')).first
      bookmark.topic ||= Topic.create(name: mail.subject.gsub(/#/, ''))

      # strip the hash tag off.
    	# look up the topic in the db
    	# get the id of the topic
    	# save the bookmark using topic id
    	# bookmark[:topic] = topic ##This just saves the topic, not the id ##
    	bookmark.url = mail.body.decoded
      Rails.logger.info ">>>> Bookmark: #{bookmark.inspect}"
    end
  	bookmark
  end
end

app/models/email_receiver.rb
class EmailReceiver < Incoming::Strategies::Mailgun
  setup :api_key => ENV['MAILGUN_API_KEY']

  def receive(mail)
    bookmark = Bookmark.new_from_email(mail)
    Rails.logger.info ">>> Bookmark is still: #{bookmark.inspect}"
    bookmark.save if bookmark
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
  attr_accessible :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  # belongs_to :user
  has_many :bookmarks
  has_many :likes
  attr_accessible :name

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :bookmarks
	has_many :likes, dependent: :destroy
	has_many :topics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :likes

  def liked(bookmark)
    self.likes.where(bookmark_id: bookmark.id).first
  end

  ROLES = %w[member moderator admin]
  def role?(base_role)
   role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # rescue_from Cancan::AccessDenied do |exception|
  # 	redirect_to root_url, :alert => exeption.message
  # end

  def after_sign_in_path_for(resource)
  	welcome_index_path
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
	before_filter :set_bookmark, except: [:index, :new, :create]

	def new
		@bookmark = Bookmark.new
	end

	def create
		@bookmark = Bookmark.new(params[:bookmark])
		@bookmark.user = current.user
		if @bookmark.save
			flash[:notice] = "Bookmark saved"
			redirect_to @bookmark
		else
			flash[:error] = "Bookmark not saved"
			# Redirect?  If so, to where?
		end
	end

	def destroy
		if @bookmark.destroy
      flash[:notice] = "Bookmark was removed."
      redirect_to welcome_index_path
    else
      flash[:error] = "Bookmark couldn't be deleted. Try again."
    end
	end

	def show
	end

	def index
		@bookmarks = Bookmark.all
	end

	private

	def set_bookmark
		@bookmark = Bookmark.find(params[:id])
	end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
  	Rails.logger.info ">>> In Email Controller, Sender is: #{params[:sender]}"
  	if EmailReceiver.receive(request)
      render :json => { :status => 'ok' }
    else
      render :json => { :status => 'rejected' }, :status => 406
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Like.all
  end

  def show
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    if current_user.likes.create(bookmark: @bookmark)
      flash[:notice] = "Bookmark liked"      
    else
      flash[:error] = "Unable to add like. Please try again."      
    end
    redirect_to welcome_index_path
  end

  def destroy
    @like = current_user.likes.find(params[:id])

    if @like.destroy
      flash[:notice] = "Removed like."
      redirect_to welcome_index_path
    else
      flash[:error] = "Unable to remove like."
      redirect_to welcome_index_path
    end
  end

end

app/controllers/topics/bookmarks_controller.rb
class BookmarksController < ApplicationController
	def index
		@bookmarks = current_user.bookmarks
	end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_filter :set_topic, except: [:index, :create]

  def create
  end

  def index
    @topics = Topic.all(:order => "updated_at DESC")
  end

  def show
  end

  def destroy
  end

  def update
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@topics = Topic.all
  	@likes = Like.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Clonemarks</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<ul class="nav nav-tabs">
				<li><%= link_to "Home", topics_path %></li>
	      <div class="pull-right user-info">
	        <% if current_user %>
	          <%= link_to "My Clonemarks", welcome_index_path %>
	          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	        <% else %>
	          <%= link_to "Sign In", new_user_session_path %> or
	          <%= link_to "Sign Up", new_user_registration_path %>
	        <% end %>
	      </div>
			</ul>
			<% if flash[:notice] %>
	        <div class="alert alert-success">
	          <button type="button" class="close" data-dismiss="alert">&times;</button>
	          <%= flash[:notice] %>
	        </div>
	      <% elsif flash[:error] %>
	        <div class="alert alert-error">
	          <button type="button" class="close" data-dismiss="alert">&times;</button>
	          <%= flash[:error] %>
	        </div>
	      <% elsif flash[:alert] %>
	        <div class="alert">
	          <button type="button" class="close" data-dismiss="alert">&times;</button>
	          <%= flash[:alert] %>
	        </div>
	      <% end %>

			<%= yield %>
		</div>

	</body>
</html>

app/views/likes/_like.html.erb
<div>
	<% if current_user %>
		<% if like = current_user.liked(bookmark) %>
			<%= link_to [bookmark, like], method: :delete do %>
				<p>Unlike</p>
			<% end %>
		<% else %>
	  	<%= link_to "Like", bookmark_likes_path(bookmark), method: :post %>
	  <% end %>
  <% end %>
</div>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/likes/show.html.erb
<h1>Likes#show</h1>
<p>Find me in app/views/likes/show.html.erb</p>

app/views/likes/update.html.erb
<h1>Likes#update</h1>
<p>Find me in app/views/likes/update.html.erb</p>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/index.html.erb
<div class="row">
	<div class="span12 text-center">
		<h1>All Clonemarks</h1>
	</div>
</div>
<% @topics.each do |topic| %>
	<div class="row">
		<div class="span12">
			<h3><%= link_to topic.name, topic %></h3>
		</div>
		<div class="row">
			<div class="span12 down40">
				<% topic.bookmarks.desc.each do |bookmark| %>
					<div class="span2">
						<div class="urlbox">
							<div class="text-center">
								<%= link_to bookmark.url, "http://#{bookmark.url}" %>
							</div>
						</div>
						<div class="text-center">
							<%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/topics/show.html.erb
<div class="row">
	<div class="span12 text-center">
		<h1><%= @topic.name %></h1>
	</div>
</div>
<div class="row">
	<div class="span12">
		<% @topic.bookmarks.desc.each do |bookmark| %>
			<div class="span3 down40">
				<div class="urlbox">
					<div class="text-center">
						<%= link_to bookmark.url, "http://#{bookmark.url}" %>
					</div>
				</div>
				<div class="text-center">
					<%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/topics/update.html.erb</p>

app/views/welcome/index.html.erb
<div class="row">
	<div class="span12 text-center">
		<h1>My Clonemarks</h1>
	</div>
</div>
<% @topics.each do |topic| %>
	<% bookmarks = topic.bookmarks.desc.select {|bookmark| bookmark.user == current_user } %>
	<% if bookmarks.any? %>
		<div class="row">
			<div class="span12">
				<h3><%= link_to topic.name, topic %></h3>
			</div>
			<div class="row">
				<div class="span12 down40">
					<% bookmarks.each do |bookmark| %>
						<div class="span2">
							<div class="urlbox">
								<div class="text-center">
									<%= link_to bookmark.url, "http://#{bookmark.url}" %>
								</div>
							</div>
							<div class="text-center">
								<%= link_to [bookmark], method: :delete do %>
									<p>Remove</p>
								<% end %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>
<% end %>
<div class="row">
	<div class="span12 text-center">
		<h1>Liked Clonemarks</h1>
	</div>
</div>
<% @topics.each do |topic| %>
	<% likes = current_user.likes.select { |like| like.bookmark.topic == topic } %>
	<% if likes.any? %>
		<div class="row">
			<div class="span12">
				<h3><%= link_to topic.name, topic %></h3>
				<% likes.each do |like| %>
					<div class="span2">
						<div class="urlbox">
							<div class="text-center">
								<%= link_to like.bookmark.url, "http://#{like.bookmark.url}" %>
							</div>
						</div>
						<div class="text-center">
							<%= render partial: 'likes/like', locals: { bookmark: like.bookmark } %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>